### ISSUE TITLE
Is this headers-only library?

### ISSUE THREAD

**Issue by elazarl** [injae/serdepp#53]
Hi,
Looking at the C++ file I can only see an empty function, which does not include anything.

Is the library headers only?

If it is, what is the purpose of the library?

**Comment by injae** [comment]
serdepp is a header-only library.
The reason we currently build as a static library is that cmake doesn't support extra dependencies(nlohmann, toml, ...) on header-only libraries.

Currently there is no option yet to build only header-library
If you want to use it as a header-only library, just add the default dependencies nameof and magic_enum and copy the include/serdepp folder.
```
find_package(nameof)
find_package(magic_enum)
include_directories(include)
```
